{
	"version": 1750569784,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/start-sheet0.png",
		"images/exit-sheet0.png",
		"images/sr-sheet0.png",
		"images/backg-sheet0.png",
		"images/bg-sheet0.png",
		"images/playerone-sheet0.png",
		"images/playerone-sheet1.png",
		"images/playerone-sheet2.png",
		"images/tiledbackground.png",
		"images/playertwo-sheet0.png",
		"images/playertwo-sheet1.png",
		"images/playertwo-sheet2.png",
		"images/player1-sheet0.png",
		"images/player2-sheet0.png",
		"images/re-sheet0.png",
		"images/re1-sheet0.png",
		"images/enemy1-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/enemy4-sheet0.png",
		"images/blood1-sheet0.png",
		"images/bar1-sheet0.png",
		"images/blood2-sheet0.png",
		"images/gameover-sheet0.png",
		"images/yes1-sheet0.png",
		"images/no1-sheet0.png",
		"images/win-sheet0.png",
		"images/back1-sheet0.png",
		"images/next-sheet0.png",
		"images/login-sheet0.png",
		"images/p1but-sheet0.png",
		"images/p2but-sheet0.png",
		"images/bg2-sheet0.png",
		"images/level-sheet0.png",
		"images/level1-sheet0.png",
		"images/level2-sheet0.png",
		"images/power1-sheet0.png",
		"images/home-sheet0.png",
		"images/bgcr-sheet0.png",
		"images/story-sheet0.png",
		"images/next2-sheet0.png",
		"images/pg-sheet0.png",
		"images/key1-sheet0.png",
		"images/key2-sheet0.png",
		"images/key3-sheet0.png",
		"images/key4-sheet0.png",
		"media/click 3.m4a",
		"media/click 3.ogg",
		"media/click sound 2.ogg",
		"media/coin sound.m4a",
		"media/coin sound.ogg",
		"media/dead sound 2.m4a",
		"media/dead sound.m4a",
		"media/dead sound.ogg",
		"media/dead-sound-2.m4a",
		"media/gameover sound.m4a",
		"media/gameover sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}